theme: jekyll-theme-cayman
plugins:
 - jekyll-titles-from-headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 
gem "github-pages", group: :jekyll_plugins

title: [The title of your site]
description: [Team Members Zixin Ma, Jiali Qian, Yidan Wang]
