theme: jekyll-theme-cayman
plugins:
 - jekyll-titles-from-headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 
gem "github-pages", group: :jekyll_plugins

#title: [Modeling and Simulation of Aerosol Flow with Mobile Sensors]
description: 
  - "Team Members: Zixin Ma, Jiali Qian, Yidan Wang"
  - "Mentors: Professor Tauhidur Rahman, PhD Tanjid Hasan Tonmoy"
tagline: |
  Team Members: Zixin Ma, Jiali Qian, Yidan Wang
  Mentors: Professor Tauhidur Rahman, PhD Tanjid Hasan Tonmoy
